import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Navbar } from '../components/Navbar';
import { Container } from '@mui/system';
import Categories from '../components/Categories';
import { Hero } from '../components/Hero';
import Cards from '../components/Cards';
import { Box, Typography } from '@mui/material';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Categories />
      {/* style={{ maxWidth: '812px', margin: '0 auto' }} */}
      <Box>
        <Hero />
      </Box>
      <Container maxWidth="lg">
        <Typography
          variant="h5"
          sx={{ fontWeight: '600', marginTop: '80px', marginBottom: '16px' }}
        >
          Top recipes
        </Typography>
      </Container>
      <Box>
        <Cards />
      </Box>
      {/* <Container maxWidth="lg">
        <main className={styles.main}>Hellooo</main>
      </Container> */}
    </div>
  );
}
