import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Navbar } from '../components/Navbar';
import { Container } from '@mui/system';
import Categories from '../components/Categories';
import { Hero } from '../components/Hero';
import Cards from '../components/Cards';
import { Box, Hidden, Typography } from '@mui/material';
import AddRecipeButton from '../components/AddRecipeButton';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        sx={{
          boxShadow: 'rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;',
          paddingBottom: '48px',
        }}
      >
        <Navbar />
        <Categories />
        {/* style={{ maxWidth: '812px', margin: '0 auto' }} */}
        <Box>
          <Hero />
        </Box>
      </Box>
      <Container maxWidth="lg">
        <Typography
          variant="h5"
          sx={{ fontWeight: '600', marginTop: '80px', marginBottom: '16px' }}
        >
          Top recipes
        </Typography>
      </Container>
      <Box>
        <Cards />
      </Box>
      <Container maxWidth="lg">
        <Typography
          variant="h5"
          sx={{ fontWeight: '600', marginTop: '80px', marginBottom: '16px' }}
        >
          Newest recipes
        </Typography>
      </Container>
      <Box>
        <Cards />
      </Box>
      <Hidden smUp>
        <Container
          maxWidth="lg"
          zIndex="100"
          sx={{
            position: 'fixed',
            bottom: '0px',
            left: '50%',
            transform: 'translateX(-50%)',
            backgroundColor: '#fff',
            zIndex: '200',
            paddingBottom: '24px',
          }}
        >
          <AddRecipeButton
            sx={{
              width: '100%',
            }}
          />
        </Container>
      </Hidden>
    </div>
  );
}
